/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: heiti18.c                                             *
* Font:        黑体                                                  *
* Height:      18                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  18                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\新建文本文档.txt *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontheiti18;

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_Fontheiti18_00B0[ 10] = { /* code 00B0, DEGREE SIGN */
  0x00, 0x00,
  0x3B, 0x00,
  0x81, 0x40,
  0x81, 0x40,
  0x2A, 0x00
};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontheiti18_7C73[ 85] = { /* code 7C73 */
  0x00, 0x00, 0xA0, 0x00, 0x00,
  0x00, 0x40, 0xA0, 0x18, 0x00,
  0x03, 0xC0, 0xA0, 0x3C, 0x00,
  0x00, 0xE0, 0xA0, 0x70, 0x00,
  0x00, 0xB0, 0xA0, 0xE0, 0x00,
  0x00, 0x10, 0xA0, 0x40, 0x00,
  0x00, 0x00, 0xA0, 0x00, 0x00,
  0x3F, 0xFF, 0xFF, 0xFF, 0xC0,
  0x00, 0x07, 0xFD, 0x00, 0x00,
  0x00, 0x0E, 0xAB, 0x00, 0x00,
  0x00, 0x1C, 0xA3, 0x80, 0x00,
  0x00, 0x38, 0xA0, 0xF0, 0x00,
  0x01, 0xF0, 0xA0, 0x7E, 0x00,
  0x1F, 0xC0, 0xA0, 0x0F, 0xC0,
  0x1E, 0x00, 0xA0, 0x01, 0x40,
  0x00, 0x00, 0xA0, 0x00, 0x00,
  0x00, 0x00, 0xB0, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontheiti18_CharInfo[2] = {
   {   5,   5,   2,   1,  18, acGUI_Fontheiti18_00B0 } /* code 00B0, DEGREE SIGN */
  ,{  18,  17,   0,   0,  18, acGUI_Fontheiti18_7C73 } /* code 7C73 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontheiti18_Prop2 = {
   0x7C73 /* first character */
  ,0x7C73 /* last character  */
  ,&GUI_Fontheiti18_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontheiti18_Prop1 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_Fontheiti18_CharInfo[  0] /* address of first character */
  ,&GUI_Fontheiti18_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontheiti18 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,18 /* height of font  */
  ,18 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontheiti18_Prop1}
  ,15 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

